//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace あかときっ_偽_.Data
{
    public partial class CharacterStatus
    {
        public long ID { get; set; }
        public string Character { get; set; }
        public float HP { get; set; }
        public float Attack { get; set; }
        public float Shield { get; set; }
        public float Speed { get; set; }
        public float Tech { get; set; }
        public string Dress { get; set; }
        public int PantsLevel { get; set; }
        public int BraLevel { get; set; }
        public int InnerLevel { get; set; }
        public int CoatLevel { get; set; }
        public int SkirtLevel { get; set; }
        public string 備考 { get; set; }
    }
    
}
