//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace あかときっ_偽_.Data
{
    public partial class Character
    {
        public long ID { get; set; }
        public string UniqueName { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string FullNameYomi { get; set; }
        public string 備考 { get; set; }
    }
    
}
