//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace あかときっ_偽_.Data
{
    public partial class Texture
    {
        public long ID { get; set; }
        public string UniqueName { get; set; }
        public string Section { get; set; }
        public string Category { get; set; }
        public string Pose { get; set; }
        public string Parts { get; set; }
        public long Level { get; set; }
        public string FileName { get; set; }
        public string 備考 { get; set; }
        public string Character { get; set; }
    }
    
}
