//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DD.UnitTest.DB
{
    public partial class MagicItem
    {
        public MagicItem()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public string Name { get; set; }
        public long ID { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
    }
    
}
