//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DD.Sample.DatabaseSample.DB
{
    public partial class Texture
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
        public string 備考 { get; set; }
        public string Section { get; set; }
        public string Category { get; set; }
        public string CharacterName { get; set; }
    
        public virtual Character Character { get; set; }
    }
    
}
